package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sicammindirizzi generated by hbm2java
 */
@Entity
@Table(name = "SICAMMIndirizzi", catalog = "Sicimi01")
public class Sicammindirizzi implements java.io.Serializable {

	private Integer saiid;
	private Sicammaziende sicammaziende;
	private Sictecnazioni sictecnazioni;
	private String saiindirizzo;
	private String saicitta;
	private String saiprovincia;
	private String saicap;
	private String sainote;
	private Boolean saidisabilitato;
	private Boolean saisedelegale;

	public Sicammindirizzi() {
	}

	public Sicammindirizzi(Sicammaziende sicammaziende,
			Sictecnazioni sictecnazioni, String saiindirizzo, String saicitta,
			String saiprovincia, String saicap, String sainote,
			Boolean saidisabilitato, Boolean saisedelegale) {
		this.sicammaziende = sicammaziende;
		this.sictecnazioni = sictecnazioni;
		this.saiindirizzo = saiindirizzo;
		this.saicitta = saicitta;
		this.saiprovincia = saiprovincia;
		this.saicap = saicap;
		this.sainote = sainote;
		this.saidisabilitato = saidisabilitato;
		this.saisedelegale = saisedelegale;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SAIid", unique = true, nullable = false)
	public Integer getSaiid() {
		return this.saiid;
	}

	public void setSaiid(Integer saiid) {
		this.saiid = saiid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAIidazienda")
	public Sicammaziende getSicammaziende() {
		return this.sicammaziende;
	}

	public void setSicammaziende(Sicammaziende sicammaziende) {
		this.sicammaziende = sicammaziende;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAInazione")
	public Sictecnazioni getSictecnazioni() {
		return this.sictecnazioni;
	}

	public void setSictecnazioni(Sictecnazioni sictecnazioni) {
		this.sictecnazioni = sictecnazioni;
	}

	@Column(name = "SAIindirizzo", length = 200)
	public String getSaiindirizzo() {
		return this.saiindirizzo;
	}

	public void setSaiindirizzo(String saiindirizzo) {
		this.saiindirizzo = saiindirizzo;
	}

	@Column(name = "SAIcitta", length = 60)
	public String getSaicitta() {
		return this.saicitta;
	}

	public void setSaicitta(String saicitta) {
		this.saicitta = saicitta;
	}

	@Column(name = "SAIprovincia", length = 60)
	public String getSaiprovincia() {
		return this.saiprovincia;
	}

	public void setSaiprovincia(String saiprovincia) {
		this.saiprovincia = saiprovincia;
	}

	@Column(name = "SAIcap", length = 20)
	public String getSaicap() {
		return this.saicap;
	}

	public void setSaicap(String saicap) {
		this.saicap = saicap;
	}

	@Column(name = "SAInote", length = 300)
	public String getSainote() {
		return this.sainote;
	}

	public void setSainote(String sainote) {
		this.sainote = sainote;
	}

	@Column(name = "SAIdisabilitato")
	public Boolean getSaidisabilitato() {
		return this.saidisabilitato;
	}

	public void setSaidisabilitato(Boolean saidisabilitato) {
		this.saidisabilitato = saidisabilitato;
	}

	@Column(name = "SAIsedelegale")
	public Boolean getSaisedelegale() {
		return this.saisedelegale;
	}

	public void setSaisedelegale(Boolean saisedelegale) {
		this.saisedelegale = saisedelegale;
	}

}
