package sicimi.api.persistence.hibernate;

// Generated Mar 4, 2013 4:32:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sicammlog generated by hbm2java
 */
@Entity
@Table(name = "SICAMMLog", catalog = "Sicimi01")
public class Sicammlog implements java.io.Serializable {

	private int idSicammlog;
	private String sqlExecuted;
	private String parametri;

	public Sicammlog() {
	}

	public Sicammlog(int idSicammlog) {
		this.idSicammlog = idSicammlog;
	}

	public Sicammlog(int idSicammlog, String sqlExecuted, String parametri) {
		this.idSicammlog = idSicammlog;
		this.sqlExecuted = sqlExecuted;
		this.parametri = parametri;
	}

	@Id
	@Column(name = "idSICAMMLog", unique = true, nullable = false)
	public int getIdSicammlog() {
		return this.idSicammlog;
	}

	public void setIdSicammlog(int idSicammlog) {
		this.idSicammlog = idSicammlog;
	}

	@Column(name = "sqlExecuted", length = 4000)
	public String getSqlExecuted() {
		return this.sqlExecuted;
	}

	public void setSqlExecuted(String sqlExecuted) {
		this.sqlExecuted = sqlExecuted;
	}

	@Column(name = "parametri", length = 4000)
	public String getParametri() {
		return this.parametri;
	}

	public void setParametri(String parametri) {
		this.parametri = parametri;
	}

}
