package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sicammpagamenti generated by hbm2java
 */
@Entity
@Table(name = "SICAMMPagamenti", catalog = "Sicimi01")
public class Sicammpagamenti implements java.io.Serializable {

	private int sapid;
	private String sappagamento;
	private String sapnote;
	private Set<Sicammaziende> sicammaziendes = new HashSet<Sicammaziende>(0);

	public Sicammpagamenti() {
	}

	public Sicammpagamenti(int sapid) {
		this.sapid = sapid;
	}

	public Sicammpagamenti(int sapid, String sappagamento, String sapnote,
			Set<Sicammaziende> sicammaziendes) {
		this.sapid = sapid;
		this.sappagamento = sappagamento;
		this.sapnote = sapnote;
		this.sicammaziendes = sicammaziendes;
	}

	@Id
	@Column(name = "SAPid", unique = true, nullable = false)
	public int getSapid() {
		return this.sapid;
	}

	public void setSapid(int sapid) {
		this.sapid = sapid;
	}

	@Column(name = "SAPpagamento")
	public String getSappagamento() {
		return this.sappagamento;
	}

	public void setSappagamento(String sappagamento) {
		this.sappagamento = sappagamento;
	}

	@Column(name = "SAPnote", length = 300)
	public String getSapnote() {
		return this.sapnote;
	}

	public void setSapnote(String sapnote) {
		this.sapnote = sapnote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammpagamenti")
	public Set<Sicammaziende> getSicammaziendes() {
		return this.sicammaziendes;
	}

	public void setSicammaziendes(Set<Sicammaziende> sicammaziendes) {
		this.sicammaziendes = sicammaziendes;
	}
	
	@Override
	public String toString() {
		return getSappagamento();
	}

}
