package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiccomddtOut generated by hbm2java
 */
@Entity
@Table(name = "SICCOMDdtOut", catalog = "Sicimi01")
public class SiccomddtOut implements java.io.Serializable {

	private Integer scdoid;
	private Integer scdonsnumero;
	private Integer scdocommessa;
	private Integer scdodestinatario;
	private Integer scdodestinazione;
	private Boolean scdocantiere;
	private Date scdodatadocumento;
	private String scdotrasportocura;
	private Integer scdovettore;
	private Byte scdocausale;
	private Integer scdofattura;

	public SiccomddtOut() {
	}

	public SiccomddtOut(Integer scdonsnumero, Integer scdocommessa,
			Integer scdodestinatario, Integer scdodestinazione,
			Boolean scdocantiere, Date scdodatadocumento,
			String scdotrasportocura, Integer scdovettore, Byte scdocausale,
			Integer scdofattura) {
		this.scdonsnumero = scdonsnumero;
		this.scdocommessa = scdocommessa;
		this.scdodestinatario = scdodestinatario;
		this.scdodestinazione = scdodestinazione;
		this.scdocantiere = scdocantiere;
		this.scdodatadocumento = scdodatadocumento;
		this.scdotrasportocura = scdotrasportocura;
		this.scdovettore = scdovettore;
		this.scdocausale = scdocausale;
		this.scdofattura = scdofattura;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCDOid", unique = true, nullable = false)
	public Integer getScdoid() {
		return this.scdoid;
	}

	public void setScdoid(Integer scdoid) {
		this.scdoid = scdoid;
	}

	@Column(name = "SCDOnsnumero")
	public Integer getScdonsnumero() {
		return this.scdonsnumero;
	}

	public void setScdonsnumero(Integer scdonsnumero) {
		this.scdonsnumero = scdonsnumero;
	}

	@Column(name = "SCDOcommessa")
	public Integer getScdocommessa() {
		return this.scdocommessa;
	}

	public void setScdocommessa(Integer scdocommessa) {
		this.scdocommessa = scdocommessa;
	}

	@Column(name = "SCDOdestinatario")
	public Integer getScdodestinatario() {
		return this.scdodestinatario;
	}

	public void setScdodestinatario(Integer scdodestinatario) {
		this.scdodestinatario = scdodestinatario;
	}

	@Column(name = "SCDOdestinazione")
	public Integer getScdodestinazione() {
		return this.scdodestinazione;
	}

	public void setScdodestinazione(Integer scdodestinazione) {
		this.scdodestinazione = scdodestinazione;
	}

	@Column(name = "SCDOcantiere")
	public Boolean getScdocantiere() {
		return this.scdocantiere;
	}

	public void setScdocantiere(Boolean scdocantiere) {
		this.scdocantiere = scdocantiere;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCDOdatadocumento", length = 0)
	public Date getScdodatadocumento() {
		return this.scdodatadocumento;
	}

	public void setScdodatadocumento(Date scdodatadocumento) {
		this.scdodatadocumento = scdodatadocumento;
	}

	@Column(name = "SCDOtrasportocura", length = 20)
	public String getScdotrasportocura() {
		return this.scdotrasportocura;
	}

	public void setScdotrasportocura(String scdotrasportocura) {
		this.scdotrasportocura = scdotrasportocura;
	}

	@Column(name = "SCDOvettore")
	public Integer getScdovettore() {
		return this.scdovettore;
	}

	public void setScdovettore(Integer scdovettore) {
		this.scdovettore = scdovettore;
	}

	@Column(name = "SCDOcausale")
	public Byte getScdocausale() {
		return this.scdocausale;
	}

	public void setScdocausale(Byte scdocausale) {
		this.scdocausale = scdocausale;
	}

	@Column(name = "SCDOfattura")
	public Integer getScdofattura() {
		return this.scdofattura;
	}

	public void setScdofattura(Integer scdofattura) {
		this.scdofattura = scdofattura;
	}

}
