package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SiccomddtInExtended generated by hbm2java
 */
@Entity
@Table(name = "SICCOMDdtInExtended", catalog = "Sicimi01")
public class SiccomddtInExtended implements java.io.Serializable {

	private SiccomddtInExtendedId id;

	public SiccomddtInExtended() {
	}

	public SiccomddtInExtended(SiccomddtInExtendedId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "scdieddtinid", column = @Column(name = "SCDIEddtinid", nullable = false)),
			@AttributeOverride(name = "scdiecommessaid", column = @Column(name = "SCDIEcommessaid", nullable = false)),
			@AttributeOverride(name = "scdieordineid", column = @Column(name = "SCDIEordineid", nullable = false)) })
	public SiccomddtInExtendedId getId() {
		return this.id;
	}

	public void setId(SiccomddtInExtendedId id) {
		this.id = id;
	}

}
