package sicimi.api.persistence.hibernate;

// Generated Mar 8, 2013 9:27:38 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SiccomfattureClientiExtended generated by hbm2java
 */
@Entity
@Table(name = "SICCOMFattureClientiExtended", catalog = "Sicimi01")
public class SiccomfattureClientiExtended implements java.io.Serializable {

	private SiccomfattureClientiExtendedId id;

	public SiccomfattureClientiExtended() {
	}

	public SiccomfattureClientiExtended(SiccomfattureClientiExtendedId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "scfceidfattura", column = @Column(name = "SCFCEidfattura", nullable = false)),
			@AttributeOverride(name = "scfceidcommessa", column = @Column(name = "SCFCEidcommessa", nullable = false)) })
	public SiccomfattureClientiExtendedId getId() {
		return this.id;
	}

	public void setId(SiccomfattureClientiExtendedId id) {
		this.id = id;
	}

}
