package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Siccomofferte generated by hbm2java
 */
@Entity
@Table(name = "SICCOMOfferte", catalog = "Sicimi01")
public class Siccomofferte implements java.io.Serializable {

	private int scoid;
	private String scoofferta;
	private Integer scoincremento;
	private Date scodata;
	private Integer scocompilatore;
	private Integer scocliente;
	private String scodescrizione;
	private Double scoimporto;
	private Short scotipo;
	private String scoattenzione;
	private String sconote;
	private Set<Sicammcommesse> sicammcommesses = new HashSet<Sicammcommesse>(0);

	public Siccomofferte() {
	}

	public Siccomofferte(int scoid) {
		this.scoid = scoid;
	}

	public Siccomofferte(int scoid, String scoofferta, Integer scoincremento,
			Date scodata, Integer scocompilatore, Integer scocliente,
			String scodescrizione, Double scoimporto, Short scotipo,
			String scoattenzione, String sconote,
			Set<Sicammcommesse> sicammcommesses) {
		this.scoid = scoid;
		this.scoofferta = scoofferta;
		this.scoincremento = scoincremento;
		this.scodata = scodata;
		this.scocompilatore = scocompilatore;
		this.scocliente = scocliente;
		this.scodescrizione = scodescrizione;
		this.scoimporto = scoimporto;
		this.scotipo = scotipo;
		this.scoattenzione = scoattenzione;
		this.sconote = sconote;
		this.sicammcommesses = sicammcommesses;
	}

	@Id
	@Column(name = "SCOid", unique = true, nullable = false)
	public int getScoid() {
		return this.scoid;
	}

	public void setScoid(int scoid) {
		this.scoid = scoid;
	}

	@Column(name = "SCOofferta", length = 13)
	public String getScoofferta() {
		return this.scoofferta;
	}

	public void setScoofferta(String scoofferta) {
		this.scoofferta = scoofferta;
	}

	@Column(name = "SCOincremento")
	public Integer getScoincremento() {
		return this.scoincremento;
	}

	public void setScoincremento(Integer scoincremento) {
		this.scoincremento = scoincremento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCOdata", length = 0)
	public Date getScodata() {
		return this.scodata;
	}

	public void setScodata(Date scodata) {
		this.scodata = scodata;
	}

	@Column(name = "SCOcompilatore")
	public Integer getScocompilatore() {
		return this.scocompilatore;
	}

	public void setScocompilatore(Integer scocompilatore) {
		this.scocompilatore = scocompilatore;
	}

	@Column(name = "SCOcliente")
	public Integer getScocliente() {
		return this.scocliente;
	}

	public void setScocliente(Integer scocliente) {
		this.scocliente = scocliente;
	}

	@Column(name = "SCOdescrizione", length = 65535)
	public String getScodescrizione() {
		return this.scodescrizione;
	}

	public void setScodescrizione(String scodescrizione) {
		this.scodescrizione = scodescrizione;
	}

	@Column(name = "SCOimporto", precision = 22, scale = 0)
	public Double getScoimporto() {
		return this.scoimporto;
	}

	public void setScoimporto(Double scoimporto) {
		this.scoimporto = scoimporto;
	}

	@Column(name = "SCOtipo")
	public Short getScotipo() {
		return this.scotipo;
	}

	public void setScotipo(Short scotipo) {
		this.scotipo = scotipo;
	}

	@Column(name = "SCOattenzione", length = 45)
	public String getScoattenzione() {
		return this.scoattenzione;
	}

	public void setScoattenzione(String scoattenzione) {
		this.scoattenzione = scoattenzione;
	}

	@Column(name = "SCOnote", length = 300)
	public String getSconote() {
		return this.sconote;
	}

	public void setSconote(String sconote) {
		this.sconote = sconote;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SICCOMOfferteExtended", catalog = "Sicimi01", joinColumns = { @JoinColumn(name = "SCFEidofferta", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "SCFEidcommessa", nullable = false, updatable = false) })
	public Set<Sicammcommesse> getSicammcommesses() {
		return this.sicammcommesses;
	}

	public void setSicammcommesses(Set<Sicammcommesse> sicammcommesses) {
		this.sicammcommesses = sicammcommesses;
	}

}
