package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiccomfattureFornitori generated by hbm2java
 */
@Entity
@Table(name = "SICCOMFattureFornitori", catalog = "Sicimi01")
public class SiccomfattureFornitori implements java.io.Serializable {

	private Integer scffid;
	private Integer scffnsnumero;
	private Integer scfffornitore;
	private Date scffdatareg;
	private Date scffdatadocumento;
	private String scffnumerodocumentofornitore;
	private Double scffimponibile;
	private Double scfftotalefattura;
	private Set<Sicammcommesse> sicammcommesses = new HashSet<Sicammcommesse>(0);

	public SiccomfattureFornitori() {
	}

	public SiccomfattureFornitori(Integer scffnsnumero, Integer scfffornitore,
			Date scffdatareg, Date scffdatadocumento,
			String scffnumerodocumentofornitore, Double scffimponibile,
			Double scfftotalefattura, Set<Sicammcommesse> sicammcommesses) {
		this.scffnsnumero = scffnsnumero;
		this.scfffornitore = scfffornitore;
		this.scffdatareg = scffdatareg;
		this.scffdatadocumento = scffdatadocumento;
		this.scffnumerodocumentofornitore = scffnumerodocumentofornitore;
		this.scffimponibile = scffimponibile;
		this.scfftotalefattura = scfftotalefattura;
		this.sicammcommesses = sicammcommesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCFFid", unique = true, nullable = false)
	public Integer getScffid() {
		return this.scffid;
	}

	public void setScffid(Integer scffid) {
		this.scffid = scffid;
	}

	@Column(name = "SCFFnsnumero")
	public Integer getScffnsnumero() {
		return this.scffnsnumero;
	}

	public void setScffnsnumero(Integer scffnsnumero) {
		this.scffnsnumero = scffnsnumero;
	}

	@Column(name = "SCFFfornitore")
	public Integer getScfffornitore() {
		return this.scfffornitore;
	}

	public void setScfffornitore(Integer scfffornitore) {
		this.scfffornitore = scfffornitore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCFFdatareg", length = 0)
	public Date getScffdatareg() {
		return this.scffdatareg;
	}

	public void setScffdatareg(Date scffdatareg) {
		this.scffdatareg = scffdatareg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCFFdatadocumento", length = 0)
	public Date getScffdatadocumento() {
		return this.scffdatadocumento;
	}

	public void setScffdatadocumento(Date scffdatadocumento) {
		this.scffdatadocumento = scffdatadocumento;
	}

	@Column(name = "SCFFnumerodocumentofornitore", length = 45)
	public String getScffnumerodocumentofornitore() {
		return this.scffnumerodocumentofornitore;
	}

	public void setScffnumerodocumentofornitore(
			String scffnumerodocumentofornitore) {
		this.scffnumerodocumentofornitore = scffnumerodocumentofornitore;
	}

	@Column(name = "SCFFimponibile", precision = 22, scale = 0)
	public Double getScffimponibile() {
		return this.scffimponibile;
	}

	public void setScffimponibile(Double scffimponibile) {
		this.scffimponibile = scffimponibile;
	}

	@Column(name = "SCFFtotalefattura", precision = 22, scale = 0)
	public Double getScfftotalefattura() {
		return this.scfftotalefattura;
	}

	public void setScfftotalefattura(Double scfftotalefattura) {
		this.scfftotalefattura = scfftotalefattura;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SICCOMFattureFornitoriExtended", catalog = "Sicimi01", joinColumns = { @JoinColumn(name = "SCFFEidfattura", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "SCFFEidcommessa", nullable = false, updatable = false) })
	public Set<Sicammcommesse> getSicammcommesses() {
		return this.sicammcommesses;
	}

	public void setSicammcommesses(Set<Sicammcommesse> sicammcommesses) {
		this.sicammcommesses = sicammcommesses;
	}

}
