package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sictecnazioni generated by hbm2java
 */
@Entity
@Table(name = "SICTECNazioni", catalog = "Sicimi01")
public class Sictecnazioni implements java.io.Serializable {

	private Integer stnid;
	private String stnnazione;
	private String stncodice;
	private String stnfrequenza;
	private String stnvoltaggio;
	private String stnnote;
	private Set<Sicammindirizzi> sicammindirizzis = new HashSet<Sicammindirizzi>(
			0);

	public Sictecnazioni() {
	}

	public Sictecnazioni(String stnnazione, String stncodice,
			String stnfrequenza, String stnvoltaggio, String stnnote,
			Set<Sicammindirizzi> sicammindirizzis) {
		this.stnnazione = stnnazione;
		this.stncodice = stncodice;
		this.stnfrequenza = stnfrequenza;
		this.stnvoltaggio = stnvoltaggio;
		this.stnnote = stnnote;
		this.sicammindirizzis = sicammindirizzis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STNid", unique = true, nullable = false)
	public Integer getStnid() {
		return this.stnid;
	}

	public void setStnid(Integer stnid) {
		this.stnid = stnid;
	}

	@Column(name = "STNnazione", length = 300)
	public String getStnnazione() {
		return this.stnnazione;
	}

	public void setStnnazione(String stnnazione) {
		this.stnnazione = stnnazione;
	}

	@Column(name = "STNcodice", length = 3)
	public String getStncodice() {
		return this.stncodice;
	}

	public void setStncodice(String stncodice) {
		this.stncodice = stncodice;
	}

	@Column(name = "STNfrequenza", length = 50)
	public String getStnfrequenza() {
		return this.stnfrequenza;
	}

	public void setStnfrequenza(String stnfrequenza) {
		this.stnfrequenza = stnfrequenza;
	}

	@Column(name = "STNvoltaggio", length = 100)
	public String getStnvoltaggio() {
		return this.stnvoltaggio;
	}

	public void setStnvoltaggio(String stnvoltaggio) {
		this.stnvoltaggio = stnvoltaggio;
	}

	@Column(name = "STNnote", length = 300)
	public String getStnnote() {
		return this.stnnote;
	}

	public void setStnnote(String stnnote) {
		this.stnnote = stnnote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sictecnazioni")
	public Set<Sicammindirizzi> getSicammindirizzis() {
		return this.sicammindirizzis;
	}

	public void setSicammindirizzis(Set<Sicammindirizzi> sicammindirizzis) {
		this.sicammindirizzis = sicammindirizzis;
	}
	
	@Override
	public String toString() {
		return getStnnazione();
	}

}
