package sicimi.api.persistence.hibernate;

// Generated Mar 8, 2013 11:51:09 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sicammaziende generated by hbm2java
 */
@Entity
@Table(name = "SICAMMAziende", catalog = "Sicimi01")
public class Sicammaziende implements java.io.Serializable {

	private int saaid;
	private Sicammindirizzi sicammindirizzi;
	private Integer saacatid;
	private String saaragionesociale;
	private String saapiva;
	private String saanote;
	private Integer saapagamentostd;
	private Set<Sicammindirizzi> sicammindirizzis = new HashSet<Sicammindirizzi>(
			0);
	private Set<Sicammcommesse> sicammcommesses = new HashSet<Sicammcommesse>(0);
	private Set<SiccomddtIn> siccomddtIns = new HashSet<SiccomddtIn>(0);

	public Sicammaziende() {
	}

	public Sicammaziende(int saaid) {
		this.saaid = saaid;
	}

	public Sicammaziende(int saaid, Sicammindirizzi sicammindirizzi,
			Integer saacatid, String saaragionesociale, String saapiva,
			String saanote, Integer saapagamentostd,
			Set<Sicammindirizzi> sicammindirizzis,
			Set<Sicammcommesse> sicammcommesses, Set<SiccomddtIn> siccomddtIns) {
		this.saaid = saaid;
		this.sicammindirizzi = sicammindirizzi;
		this.saacatid = saacatid;
		this.saaragionesociale = saaragionesociale;
		this.saapiva = saapiva;
		this.saanote = saanote;
		this.saapagamentostd = saapagamentostd;
		this.sicammindirizzis = sicammindirizzis;
		this.sicammcommesses = sicammcommesses;
		this.siccomddtIns = siccomddtIns;
	}

	@Id
	@Column(name = "SAAid", unique = true, nullable = false)
	public int getSaaid() {
		return this.saaid;
	}

	public void setSaaid(int saaid) {
		this.saaid = saaid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAAindirizzostd")
	public Sicammindirizzi getSicammindirizzi() {
		return this.sicammindirizzi;
	}

	public void setSicammindirizzi(Sicammindirizzi sicammindirizzi) {
		this.sicammindirizzi = sicammindirizzi;
	}

	@Column(name = "SAAcatid")
	public Integer getSaacatid() {
		return this.saacatid;
	}

	public void setSaacatid(Integer saacatid) {
		this.saacatid = saacatid;
	}

	@Column(name = "SAAragionesociale", length = 100)
	public String getSaaragionesociale() {
		return this.saaragionesociale;
	}

	public void setSaaragionesociale(String saaragionesociale) {
		this.saaragionesociale = saaragionesociale;
	}

	@Column(name = "SAApiva", length = 11)
	public String getSaapiva() {
		return this.saapiva;
	}

	public void setSaapiva(String saapiva) {
		this.saapiva = saapiva;
	}

	@Column(name = "SAAnote", length = 300)
	public String getSaanote() {
		return this.saanote;
	}

	public void setSaanote(String saanote) {
		this.saanote = saanote;
	}

	@Column(name = "SAApagamentostd")
	public Integer getSaapagamentostd() {
		return this.saapagamentostd;
	}

	public void setSaapagamentostd(Integer saapagamentostd) {
		this.saapagamentostd = saapagamentostd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziende")
	public Set<Sicammindirizzi> getSicammindirizzis() {
		return this.sicammindirizzis;
	}

	public void setSicammindirizzis(Set<Sicammindirizzi> sicammindirizzis) {
		this.sicammindirizzis = sicammindirizzis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziende")
	public Set<Sicammcommesse> getSicammcommesses() {
		return this.sicammcommesses;
	}

	public void setSicammcommesses(Set<Sicammcommesse> sicammcommesses) {
		this.sicammcommesses = sicammcommesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziende")
	public Set<SiccomddtIn> getSiccomddtIns() {
		return this.siccomddtIns;
	}

	public void setSiccomddtIns(Set<SiccomddtIn> siccomddtIns) {
		this.siccomddtIns = siccomddtIns;
	}

}
