package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sicammaziende generated by hbm2java
 */
@Entity
@Table(name = "SICAMMAziende", catalog = "Sicimi01")
public class Sicammaziende implements java.io.Serializable {

	private Integer saaid;
	private Sicammpagamenti sicammpagamenti;
	private Integer saacatid;
	private String saaragionesociale;
	private String saapiva;
	private String saanote;
	private Set<Sicammcommesse> sicammcommessesForSaccliente = new HashSet<Sicammcommesse>(
			0);
	private Set<Sicammindirizzi> sicammindirizzis = new HashSet<Sicammindirizzi>(
			0);
	private Set<Sicammcommesse> sicammcommessesForSacdestinazione = new HashSet<Sicammcommesse>(
			0);
	private Set<SiccomddtIn> siccomddtIns = new HashSet<SiccomddtIn>(0);

	public Sicammaziende() {
	}

	public Sicammaziende(Sicammpagamenti sicammpagamenti, Integer saacatid,
			String saaragionesociale, String saapiva, String saanote,
			Set<Sicammcommesse> sicammcommessesForSaccliente,
			Set<Sicammindirizzi> sicammindirizzis,
			Set<Sicammcommesse> sicammcommessesForSacdestinazione,
			Set<SiccomddtIn> siccomddtIns) {
		this.sicammpagamenti = sicammpagamenti;
		this.saacatid = saacatid;
		this.saaragionesociale = saaragionesociale;
		this.saapiva = saapiva;
		this.saanote = saanote;
		this.sicammcommessesForSaccliente = sicammcommessesForSaccliente;
		this.sicammindirizzis = sicammindirizzis;
		this.sicammcommessesForSacdestinazione = sicammcommessesForSacdestinazione;
		this.siccomddtIns = siccomddtIns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SAAid", unique = true, nullable = false)
	public Integer getSaaid() {
		return this.saaid;
	}

	public void setSaaid(Integer saaid) {
		this.saaid = saaid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAApagamentostd")
	public Sicammpagamenti getSicammpagamenti() {
		return this.sicammpagamenti;
	}

	public void setSicammpagamenti(Sicammpagamenti sicammpagamenti) {
		this.sicammpagamenti = sicammpagamenti;
	}

	@Column(name = "SAAcatid")
	public Integer getSaacatid() {
		return this.saacatid;
	}

	public void setSaacatid(Integer saacatid) {
		this.saacatid = saacatid;
	}

	@Column(name = "SAAragionesociale", length = 100)
	public String getSaaragionesociale() {
		return this.saaragionesociale;
	}

	public void setSaaragionesociale(String saaragionesociale) {
		this.saaragionesociale = saaragionesociale;
	}

	@Column(name = "SAApiva", length = 11)
	public String getSaapiva() {
		return this.saapiva;
	}

	public void setSaapiva(String saapiva) {
		this.saapiva = saapiva;
	}

	@Column(name = "SAAnote", length = 300)
	public String getSaanote() {
		return this.saanote;
	}

	public void setSaanote(String saanote) {
		this.saanote = saanote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziendeBySaccliente")
	public Set<Sicammcommesse> getSicammcommessesForSaccliente() {
		return this.sicammcommessesForSaccliente;
	}

	public void setSicammcommessesForSaccliente(
			Set<Sicammcommesse> sicammcommessesForSaccliente) {
		this.sicammcommessesForSaccliente = sicammcommessesForSaccliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziende")
	public Set<Sicammindirizzi> getSicammindirizzis() {
		return this.sicammindirizzis;
	}

	public void setSicammindirizzis(Set<Sicammindirizzi> sicammindirizzis) {
		this.sicammindirizzis = sicammindirizzis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziendeBySacdestinazione")
	public Set<Sicammcommesse> getSicammcommessesForSacdestinazione() {
		return this.sicammcommessesForSacdestinazione;
	}

	public void setSicammcommessesForSacdestinazione(
			Set<Sicammcommesse> sicammcommessesForSacdestinazione) {
		this.sicammcommessesForSacdestinazione = sicammcommessesForSacdestinazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sicammaziende")
	public Set<SiccomddtIn> getSiccomddtIns() {
		return this.siccomddtIns;
	}

	public void setSiccomddtIns(Set<SiccomddtIn> siccomddtIns) {
		this.siccomddtIns = siccomddtIns;
	}
	
	@Override
	public String toString() {
		return saaragionesociale;
	}

}
