package sicimi.api.persistence.hibernate;

// Generated Feb 28, 2013 2:34:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sicammlog generated by hbm2java
 */
@Entity
@Table(name = "SICAMMLog", catalog = "Sicimi01")
public class Sicammlog implements java.io.Serializable {

	private int idSicammlog;
	private String sql;
	private String parametri;

	public Sicammlog() {
	}

	public Sicammlog(int idSicammlog) {
		this.idSicammlog = idSicammlog;
	}

	public Sicammlog(int idSicammlog, String sql, String parametri) {
		this.idSicammlog = idSicammlog;
		this.sql = sql;
		this.parametri = parametri;
	}

	@Id
	@Column(name = "idSICAMMLog", unique = true, nullable = false)
	public int getIdSicammlog() {
		return this.idSicammlog;
	}

	public void setIdSicammlog(int idSicammlog) {
		this.idSicammlog = idSicammlog;
	}

	@Column(name = "sql", length = 45)
	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	@Column(name = "parametri", length = 45)
	public String getParametri() {
		return this.parametri;
	}

	public void setParametri(String parametri) {
		this.parametri = parametri;
	}

}
