package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sicammcategorie generated by hbm2java
 */
@Entity
@Table(name = "SICAMMCategorie", catalog = "Sicimi01")
public class Sicammcategorie implements java.io.Serializable {

	private int saeid;
	private String saecategoria;

	public Sicammcategorie() {
	}

	public Sicammcategorie(int saeid) {
		this.saeid = saeid;
	}

	public Sicammcategorie(int saeid, String saecategoria) {
		this.saeid = saeid;
		this.saecategoria = saecategoria;
	}

	@Id
	@Column(name = "SAEid", unique = true, nullable = false)
	public int getSaeid() {
		return this.saeid;
	}

	public void setSaeid(int saeid) {
		this.saeid = saeid;
	}

	@Column(name = "SAEcategoria", length = 45)
	public String getSaecategoria() {
		return this.saecategoria;
	}

	public void setSaecategoria(String saecategoria) {
		this.saecategoria = saecategoria;
	}

}
