package sicimi.api.persistence.hibernate;

// Generated Mar 8, 2013 11:51:09 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiccomfattureClienti generated by hbm2java
 */
@Entity
@Table(name = "SICCOMFattureClienti", catalog = "Sicimi01")
public class SiccomfattureClienti implements java.io.Serializable {

	private Integer scfcid;
	private Integer scfcnsnumero;
	private Integer scfccliente;
	private Date scfcdatadocumento;
	private Integer scfcpagamento;
	private String scfcdescrizione1;
	private String scfcdescrizione2;
	private String scfcnote;
	private Double scfcimponibile;
	private Integer scfcaliquota;
	private Double scfciva;
	private Double scfcbollo;
	private Double scfctotale;
	private Set<Sicammcommesse> sicammcommesses = new HashSet<Sicammcommesse>(0);

	public SiccomfattureClienti() {
	}

	public SiccomfattureClienti(Integer scfcnsnumero, Integer scfccliente,
			Date scfcdatadocumento, Integer scfcpagamento,
			String scfcdescrizione1, String scfcdescrizione2, String scfcnote,
			Double scfcimponibile, Integer scfcaliquota, Double scfciva,
			Double scfcbollo, Double scfctotale,
			Set<Sicammcommesse> sicammcommesses) {
		this.scfcnsnumero = scfcnsnumero;
		this.scfccliente = scfccliente;
		this.scfcdatadocumento = scfcdatadocumento;
		this.scfcpagamento = scfcpagamento;
		this.scfcdescrizione1 = scfcdescrizione1;
		this.scfcdescrizione2 = scfcdescrizione2;
		this.scfcnote = scfcnote;
		this.scfcimponibile = scfcimponibile;
		this.scfcaliquota = scfcaliquota;
		this.scfciva = scfciva;
		this.scfcbollo = scfcbollo;
		this.scfctotale = scfctotale;
		this.sicammcommesses = sicammcommesses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCFCid", unique = true, nullable = false)
	public Integer getScfcid() {
		return this.scfcid;
	}

	public void setScfcid(Integer scfcid) {
		this.scfcid = scfcid;
	}

	@Column(name = "SCFCnsnumero")
	public Integer getScfcnsnumero() {
		return this.scfcnsnumero;
	}

	public void setScfcnsnumero(Integer scfcnsnumero) {
		this.scfcnsnumero = scfcnsnumero;
	}

	@Column(name = "SCFCcliente")
	public Integer getScfccliente() {
		return this.scfccliente;
	}

	public void setScfccliente(Integer scfccliente) {
		this.scfccliente = scfccliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCFCdatadocumento", length = 0)
	public Date getScfcdatadocumento() {
		return this.scfcdatadocumento;
	}

	public void setScfcdatadocumento(Date scfcdatadocumento) {
		this.scfcdatadocumento = scfcdatadocumento;
	}

	@Column(name = "SCFCpagamento")
	public Integer getScfcpagamento() {
		return this.scfcpagamento;
	}

	public void setScfcpagamento(Integer scfcpagamento) {
		this.scfcpagamento = scfcpagamento;
	}

	@Column(name = "SCFCdescrizione1", length = 500)
	public String getScfcdescrizione1() {
		return this.scfcdescrizione1;
	}

	public void setScfcdescrizione1(String scfcdescrizione1) {
		this.scfcdescrizione1 = scfcdescrizione1;
	}

	@Column(name = "SCFCdescrizione2", length = 500)
	public String getScfcdescrizione2() {
		return this.scfcdescrizione2;
	}

	public void setScfcdescrizione2(String scfcdescrizione2) {
		this.scfcdescrizione2 = scfcdescrizione2;
	}

	@Column(name = "SCFCnote", length = 45)
	public String getScfcnote() {
		return this.scfcnote;
	}

	public void setScfcnote(String scfcnote) {
		this.scfcnote = scfcnote;
	}

	@Column(name = "SCFCimponibile", precision = 22, scale = 0)
	public Double getScfcimponibile() {
		return this.scfcimponibile;
	}

	public void setScfcimponibile(Double scfcimponibile) {
		this.scfcimponibile = scfcimponibile;
	}

	@Column(name = "SCFCaliquota")
	public Integer getScfcaliquota() {
		return this.scfcaliquota;
	}

	public void setScfcaliquota(Integer scfcaliquota) {
		this.scfcaliquota = scfcaliquota;
	}

	@Column(name = "SCFCiva", precision = 22, scale = 0)
	public Double getScfciva() {
		return this.scfciva;
	}

	public void setScfciva(Double scfciva) {
		this.scfciva = scfciva;
	}

	@Column(name = "SCFCbollo", precision = 22, scale = 0)
	public Double getScfcbollo() {
		return this.scfcbollo;
	}

	public void setScfcbollo(Double scfcbollo) {
		this.scfcbollo = scfcbollo;
	}

	@Column(name = "SCFCtotale", precision = 22, scale = 0)
	public Double getScfctotale() {
		return this.scfctotale;
	}

	public void setScfctotale(Double scfctotale) {
		this.scfctotale = scfctotale;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SICCOMFattureClientiExtended", catalog = "Sicimi01", joinColumns = { @JoinColumn(name = "SCFCEidfattura", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "SCFCEidcommessa", nullable = false, updatable = false) })
	public Set<Sicammcommesse> getSicammcommesses() {
		return this.sicammcommesses;
	}

	public void setSicammcommesses(Set<Sicammcommesse> sicammcommesses) {
		this.sicammcommesses = sicammcommesses;
	}

}
