package sicimi.api.persistence.hibernate;

// Generated Mar 4, 2013 4:32:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Siccomordini generated by hbm2java
 */
@Entity
@Table(name = "SICCOMOrdini", catalog = "Sicimi01")
public class Siccomordini implements java.io.Serializable {

	private Integer scrid;
	private String scrordine;
	private Integer scrincremento;
	private Date scrdata;
	private Integer scrcompilatore;
	private Integer scrcommessa;
	private Integer scrfornitore;
	private Date scrconsegna;
	private Double scrimporto;
	private Byte scrtrasporto;
	private String scrconsegnato;
	private String scrriferimento;
	private Integer scrpagamento;
	private Byte scrbanca;
	private String scrcattenzione;
	private String scrnote;
	private String screliminato;

	public Siccomordini() {
	}

	public Siccomordini(String scrordine, Integer scrincremento, Date scrdata,
			Integer scrcompilatore, Integer scrcommessa, Integer scrfornitore,
			Date scrconsegna, Double scrimporto, Byte scrtrasporto,
			String scrconsegnato, String scrriferimento, Integer scrpagamento,
			Byte scrbanca, String scrcattenzione, String scrnote,
			String screliminato) {
		this.scrordine = scrordine;
		this.scrincremento = scrincremento;
		this.scrdata = scrdata;
		this.scrcompilatore = scrcompilatore;
		this.scrcommessa = scrcommessa;
		this.scrfornitore = scrfornitore;
		this.scrconsegna = scrconsegna;
		this.scrimporto = scrimporto;
		this.scrtrasporto = scrtrasporto;
		this.scrconsegnato = scrconsegnato;
		this.scrriferimento = scrriferimento;
		this.scrpagamento = scrpagamento;
		this.scrbanca = scrbanca;
		this.scrcattenzione = scrcattenzione;
		this.scrnote = scrnote;
		this.screliminato = screliminato;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCRid", unique = true, nullable = false)
	public Integer getScrid() {
		return this.scrid;
	}

	public void setScrid(Integer scrid) {
		this.scrid = scrid;
	}

	@Column(name = "SCRordine", length = 17)
	public String getScrordine() {
		return this.scrordine;
	}

	public void setScrordine(String scrordine) {
		this.scrordine = scrordine;
	}

	@Column(name = "SCRincremento")
	public Integer getScrincremento() {
		return this.scrincremento;
	}

	public void setScrincremento(Integer scrincremento) {
		this.scrincremento = scrincremento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCRdata", length = 10)
	public Date getScrdata() {
		return this.scrdata;
	}

	public void setScrdata(Date scrdata) {
		this.scrdata = scrdata;
	}

	@Column(name = "SCRcompilatore")
	public Integer getScrcompilatore() {
		return this.scrcompilatore;
	}

	public void setScrcompilatore(Integer scrcompilatore) {
		this.scrcompilatore = scrcompilatore;
	}

	@Column(name = "SCRcommessa")
	public Integer getScrcommessa() {
		return this.scrcommessa;
	}

	public void setScrcommessa(Integer scrcommessa) {
		this.scrcommessa = scrcommessa;
	}

	@Column(name = "SCRfornitore")
	public Integer getScrfornitore() {
		return this.scrfornitore;
	}

	public void setScrfornitore(Integer scrfornitore) {
		this.scrfornitore = scrfornitore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCRconsegna", length = 10)
	public Date getScrconsegna() {
		return this.scrconsegna;
	}

	public void setScrconsegna(Date scrconsegna) {
		this.scrconsegna = scrconsegna;
	}

	@Column(name = "SCRimporto", precision = 22, scale = 0)
	public Double getScrimporto() {
		return this.scrimporto;
	}

	public void setScrimporto(Double scrimporto) {
		this.scrimporto = scrimporto;
	}

	@Column(name = "SCRtrasporto")
	public Byte getScrtrasporto() {
		return this.scrtrasporto;
	}

	public void setScrtrasporto(Byte scrtrasporto) {
		this.scrtrasporto = scrtrasporto;
	}

	@Column(name = "SCRconsegnato", length = 2)
	public String getScrconsegnato() {
		return this.scrconsegnato;
	}

	public void setScrconsegnato(String scrconsegnato) {
		this.scrconsegnato = scrconsegnato;
	}

	@Column(name = "SCRriferimento", length = 65535)
	public String getScrriferimento() {
		return this.scrriferimento;
	}

	public void setScrriferimento(String scrriferimento) {
		this.scrriferimento = scrriferimento;
	}

	@Column(name = "SCRpagamento")
	public Integer getScrpagamento() {
		return this.scrpagamento;
	}

	public void setScrpagamento(Integer scrpagamento) {
		this.scrpagamento = scrpagamento;
	}

	@Column(name = "SCRbanca")
	public Byte getScrbanca() {
		return this.scrbanca;
	}

	public void setScrbanca(Byte scrbanca) {
		this.scrbanca = scrbanca;
	}

	@Column(name = "SCRcattenzione", length = 100)
	public String getScrcattenzione() {
		return this.scrcattenzione;
	}

	public void setScrcattenzione(String scrcattenzione) {
		this.scrcattenzione = scrcattenzione;
	}

	@Column(name = "SCRnote", length = 500)
	public String getScrnote() {
		return this.scrnote;
	}

	public void setScrnote(String scrnote) {
		this.scrnote = scrnote;
	}

	@Column(name = "SCReliminato", length = 2)
	public String getScreliminato() {
		return this.screliminato;
	}

	public void setScreliminato(String screliminato) {
		this.screliminato = screliminato;
	}

}
