package sicimi.api.persistence.hibernate;

// Generated Mar 15, 2013 4:48:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SictecnumeriFabbrica generated by hbm2java
 */
@Entity
@Table(name = "SICTECNumeriFabbrica", catalog = "Sicimi01")
public class SictecnumeriFabbrica implements java.io.Serializable {

	private int stnfid;
	private Sicammcommesse sicammcommesse;
	private String stnfdescrizione;
	private String stnfdisegno;
	private String stnfped;
	private Integer stnfcliente;
	private String stnftipo;
	private String stnfcodcostruzione;
	private String stnfmodulo;
	private String stnftstmin;
	private String stnftstmax;
	private String stnftssmin;
	private String stnftssmax;
	private String stnfpst;
	private String stnfpss;

	public SictecnumeriFabbrica() {
	}

	public SictecnumeriFabbrica(int stnfid) {
		this.stnfid = stnfid;
	}

	public SictecnumeriFabbrica(int stnfid, Sicammcommesse sicammcommesse,
			String stnfdescrizione, String stnfdisegno, String stnfped,
			Integer stnfcliente, String stnftipo, String stnfcodcostruzione,
			String stnfmodulo, String stnftstmin, String stnftstmax,
			String stnftssmin, String stnftssmax, String stnfpst, String stnfpss) {
		this.stnfid = stnfid;
		this.sicammcommesse = sicammcommesse;
		this.stnfdescrizione = stnfdescrizione;
		this.stnfdisegno = stnfdisegno;
		this.stnfped = stnfped;
		this.stnfcliente = stnfcliente;
		this.stnftipo = stnftipo;
		this.stnfcodcostruzione = stnfcodcostruzione;
		this.stnfmodulo = stnfmodulo;
		this.stnftstmin = stnftstmin;
		this.stnftstmax = stnftstmax;
		this.stnftssmin = stnftssmin;
		this.stnftssmax = stnftssmax;
		this.stnfpst = stnfpst;
		this.stnfpss = stnfpss;
	}

	@Id
	@Column(name = "STNFid", unique = true, nullable = false)
	public int getStnfid() {
		return this.stnfid;
	}

	public void setStnfid(int stnfid) {
		this.stnfid = stnfid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STNFcommessa")
	public Sicammcommesse getSicammcommesse() {
		return this.sicammcommesse;
	}

	public void setSicammcommesse(Sicammcommesse sicammcommesse) {
		this.sicammcommesse = sicammcommesse;
	}

	@Column(name = "STNFdescrizione", length = 65535)
	public String getStnfdescrizione() {
		return this.stnfdescrizione;
	}

	public void setStnfdescrizione(String stnfdescrizione) {
		this.stnfdescrizione = stnfdescrizione;
	}

	@Column(name = "STNFdisegno", length = 40)
	public String getStnfdisegno() {
		return this.stnfdisegno;
	}

	public void setStnfdisegno(String stnfdisegno) {
		this.stnfdisegno = stnfdisegno;
	}

	@Column(name = "STNFped", length = 40)
	public String getStnfped() {
		return this.stnfped;
	}

	public void setStnfped(String stnfped) {
		this.stnfped = stnfped;
	}

	@Column(name = "STNFcliente")
	public Integer getStnfcliente() {
		return this.stnfcliente;
	}

	public void setStnfcliente(Integer stnfcliente) {
		this.stnfcliente = stnfcliente;
	}

	@Column(name = "STNFtipo")
	public String getStnftipo() {
		return this.stnftipo;
	}

	public void setStnftipo(String stnftipo) {
		this.stnftipo = stnftipo;
	}

	@Column(name = "STNFcodcostruzione", length = 40)
	public String getStnfcodcostruzione() {
		return this.stnfcodcostruzione;
	}

	public void setStnfcodcostruzione(String stnfcodcostruzione) {
		this.stnfcodcostruzione = stnfcodcostruzione;
	}

	@Column(name = "STNFmodulo", length = 40)
	public String getStnfmodulo() {
		return this.stnfmodulo;
	}

	public void setStnfmodulo(String stnfmodulo) {
		this.stnfmodulo = stnfmodulo;
	}

	@Column(name = "STNFtstmin", length = 10)
	public String getStnftstmin() {
		return this.stnftstmin;
	}

	public void setStnftstmin(String stnftstmin) {
		this.stnftstmin = stnftstmin;
	}

	@Column(name = "STNFtstmax", length = 10)
	public String getStnftstmax() {
		return this.stnftstmax;
	}

	public void setStnftstmax(String stnftstmax) {
		this.stnftstmax = stnftstmax;
	}

	@Column(name = "STNFtssmin", length = 10)
	public String getStnftssmin() {
		return this.stnftssmin;
	}

	public void setStnftssmin(String stnftssmin) {
		this.stnftssmin = stnftssmin;
	}

	@Column(name = "STNFtssmax", length = 10)
	public String getStnftssmax() {
		return this.stnftssmax;
	}

	public void setStnftssmax(String stnftssmax) {
		this.stnftssmax = stnftssmax;
	}

	@Column(name = "STNFpst", length = 10)
	public String getStnfpst() {
		return this.stnfpst;
	}

	public void setStnfpst(String stnfpst) {
		this.stnfpst = stnfpst;
	}

	@Column(name = "STNFpss", length = 10)
	public String getStnfpss() {
		return this.stnfpss;
	}

	public void setStnfpss(String stnfpss) {
		this.stnfpss = stnfpss;
	}

}
